<?php


function out_of_stock_help($path, $arg)
{
    switch ($path) {
        case "admin/help#out_of_stock":
            return t("Mostrar links a una pagina ");
            break;
    }
}
/**
 * Implements hook_menu().
 */
function out_of_stock_menu() {
    $items = array();

    $items['admin/config/content/out_of_stock'] = array(
        'title' => 'Out of stock',
        'description' => 'Configuration for Out of stock module',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('out_of_stock_form'),
        'access arguments' => array('access administration pages'),
        'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}

/**
 * Implements hook_contents().
 */
function out_of_stock_contents() {

    //Use Database API to retrieve current posts.
    //fiel data commerce products
    $query = db_select('field_data_commerce_stock', 'n')
        ->fields('n')
        ->condition('commerce_stock_value', 0) //Condicion de stock a cero
        ->execute();
    return $query;
}
/**
 * Implements hook_block_view().
 *
 * Prepares the contents of the block.
 */
function out_of_stock_block_view($delta = '') {
    switch ($delta) {
        case 'out_of_stock':
            $block['subject'] = t('Out of stock');
            if (user_access('access content')) {
                // Use our custom function to retrieve data.
                $result = out_of_stock_contents();
                // Array to contain items for the block to render.
                $items = array();
                // Iterate over the resultset and format as links.
                foreach ($result as $node) {
                    //cogemos el producto
                    $producto = commerce_product_load($node->entity_id);
                    $items[] = array(
                        'data' => l( $producto->title, 'admin/commerce/products/'
                            . $node->entity_id . '/edit'),
                    );
                }
                // No content in the last week.
                if (empty($items)) {
                    $block['content'] = t('No products available.');
                }
                else {
                    // Pass data through theme function.
                    try {
                        $block['content'] = theme('item_list', array(
                            'items' => $items));
                    } catch (Exception $e) {
                        echo $e;
                    }
                }
                break;
            }
            return $block;
    }

}


/**
 * Implements hook_permission().
 */
function out_of_stock_permission() {
    return array(
        'access out_of_stock content' => array(
            'title' => t('Access content for the Out of Stock module'),
        )
    );
}

/**
 * Page callback: Current posts settings
 *
 * @see current_posts_menu()

function out_of_stock_form($form, &$form_state) {
$form['out_of_stock_max'] = array(
'#type' => 'textfield',
'#title' => t('Products with this stock left and less'),
'#default_value' => variable_get('out_of_stock_max', 3),
'#size' => 2,
'#maxlength' => 2,
'#description' => t('The maximum number of links to display in the block.'),
'#required' => TRUE,
);

return system_settings_form($form);
}
 */
/**
 * Implements validation from the Form API.
 *
 * @param $form
 *   A structured array containing the elements and properties of the form.
 * @param $form_state
 *   An array that stores information about the form's current state
 *   during processing.

function out_of_stock_form_validate($form, &$form_state){
$max_num = $form_state['values']['out_of_stock_max'];
if (!is_numeric($max_num)){
form_set_error('out_of_stock_max', t('You must enter a number for the maximum number of stock.'));
}
elseif ($max_num <= 0){
form_set_error('out_of_stock_max', t('Maximum number of stock to display must be positive.'));
}
}
 */
/**
 * Mostrar pagina

function out_of_stock_pagina(){
$items=array();
$items['pagina']=array(
'title'=>'Out of Stock Page',
'description'=>'Esto es una prueba',
'page callback'=>'drupal_get_forms',
'page arguments'=>array('drupal_get_form'),
'access callbacks'=>'user_access',
'access arguments'=>array('access content'),
'type'=>MENU_NORMAL_ITEM

);
}
 */
